#!/usr/bin/env python3
from ev3dev2 . motor import *
#!/usr/bin/env python3
from ev3dev2 . motor import *
from ev3dev2.sensor.lego import ColorSensor
from ev3dev2.sound import Sound
from time import sleep

cl = ColorSensor()
cl.mode = 'COL-COLOR'
drive = MoveTank ( OUTPUT_B,OUTPUT_C )
# Attach large motors to ports B and C
mB = LargeMotor('outB')
mC = LargeMotor('outC')

count = 0
sound = Sound()

while True:
        if count <1:
            drive.on_for_rotations(SpeedPercent(20), SpeedPercent(20), 0.7);
        if cl.color ==1:
            count += 1
            if count == 1:
                mB.run_to_rel_pos(position_sp=340, speed_sp=360, stop_action="brake")
                sound.speak(count)
                drive.on_for_rotations(SpeedPercent(20), SpeedPercent(20), 0.7)
            elif count == 7:
                mB.run_to_rel_pos(position_sp=340, speed_sp=360, stop_action="brake")
                sound.speak(count)
                drive.on_for_rotations(SpeedPercent(20), SpeedPercent(20), 0.7)
            elif count == 13:
                mC.run_to_rel_pos(position_sp=340, speed_sp=360, stop_action="brake")
                sound.speak(count)
            else:
                sound.speak(count)
                drive.on_for_rotations(SpeedPercent(20), SpeedPercent(20), 0.7)
        elif cl.color!=1:
            drive.on_for_rotations(SpeedPercent(20), SpeedPercent(20), 0.7)

sleep (2)
